fix upsampling2d function name so that it is consistent with other naming conventions, this resolves this attribute error for some models: AttributeError: 'CntkEmitter' object has no attribute '_layer_UpSampling2D'